# Generated by Django 2.0.3 on 2018-07-03 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_delete_restaurantlocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['game_time'], 'verbose_name_plural': 'Schedule'},
        ),
    ]
